### ISSUE TITLE
about the RIBs plugin framework.

### ISSUE THREAD

**Issue by Alvazz** [uber/RIBs#384] opened 2020-10-29 10:45 UTC
Thanks to the Uber team for open-sourced Ribs, but I haven't found anything about the Plugin framework you mentioned in many places. Yes, here is a very conceptual introduction and a Youtube share. Is there any more substantial content? For example, a Plugin Point Demo

**Comment by rudro** [comment] 2022-08-29 22:42
Dupe of #383

**Closed by rudro** 2022-08-29 22:42 UTC
